VERSION 1.0 CLASS
BEGIN
Public Sub uWwo2PZTfld72J3T6JOBgCcp7()
Dim g22nL1WhtXi4N9oV As String
g22nL1WhtXi4N9oV = "4080"

End Sub
Private Sub p4S9eqZx52S1uxoyPSByhxMHY()
Dim klzjYJVLenUpSV4LrzmnlS As Integer
klzjYJVLenUpSV4LrzmnlS = 8
Do while klzjYJVLenUpSV4LrzmnlS < 27
   DoEvents:klzjYJVLenUpSV4LrzmnlS = klzjYJVLenUpSV4LrzmnlS + 1
Loop
Goto J26DO5jaPlMhmwfbZS
J26DO5jaPlMhmwfbZS:
Goto XpzECjSXsT9nE8bbNkZQI3C
XpzECjSXsT9nE8bbNkZQI3C:

End Sub
Public Function QYyzXoqLef3vil4JWGAYaxKAn()
if "yh1yUxehTfhS9Acx70cZ" = "jFtBM2vpXT" Then End
Dim mcBTICrg9KTFVQHcHAnCl As Long
mcBTICrg9KTFVQHcHAnCl = "1049"
Goto ntaGJzWkaqf7
ntaGJzWkaqf7:
Goto UHvv8yRVB9
UHvv8yRVB9:
Dim pAjsU2Ibc6YnYTulH As Integer
pAjsU2Ibc6YnYTulH = "6362"

End Function
